### ISSUE TITLE
是否有方案替换项目中RabbitMQ方式

### ISSUE THREAD

**Issue by chenzuo** [RayTale/Ray#1]
我建议换掉RabbitMQ。

**Comment by chenzuo** [comment]
建议用一个更容易的方案实现，毕竟在demo阶段没有人愿意用这么重的东西

**Comment by u-less** [comment]
@chenzuo 都是依赖注入进来的，可以方便的替换，我抽空实现一个基于内存的

**Comment by chenzuo** [comment]
大概什么时候能好，一直在关注！
