### ISSUE TITLE
拉取源码重新生成解决方案，发生报错。大大，怎么破？

### ISSUE THREAD

**Issue by GuDuYing** [RayTale/Ray#13]
![image](https://user-images.githubusercontent.com/18617550/44329695-a7617880-a497-11e8-95ff-c9d4a89d10ed.png)
好像接口使用了ValueTask类型，实现却是使用了Task，这是？？？求解答，大大

**Comment by u-less** [comment]
@GuDuYing 建议使用Postgresql组件，Mongodb还没有针对新的改动进行大量测试

**Comment by u-less** [comment]
@GuDuYing 错误的代码已经修复

**Comment by GuDuYing** [comment]
好的 谢谢大大

**Comment by iEricZHENG** [comment]
第二个错误MSB3073是多了一个nuget包，可以重新拉一下源码，可以编译通过了。

**Comment by newbe36524** [comment]
@CharlesZHENG 这都移除了，那怎么快乐的使用。
![image](https://user-images.githubusercontent.com/7685462/44656790-e27e2180-aa2c-11e8-9358-432debc73717.png)

**Comment by iEricZHENG** [comment]
@newbe36524 谢谢指正，重新添加回去了。
