### ISSUE TITLE
下载代码编译不通过

### ISSUE THREAD

**Issue by sunriseyuen** [RayTale/Ray#14]
`严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3073	命令“"dotnet" "C:\Users\sunrise\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0\build\..\tasks\netcoreapp2.0\Orleans.CodeGeneration.Build.dll" "@obj\Debug\netstandard2.0\codegen\Ray.IGrains.orleans.g.args.txt"”已退出，代码为 3。	Ray.IGrains	C:\Users\sunrise\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets	82	

`

是不是哪里做错了？

**Comment by newbe36524** [comment]
donet core 2.1 运行时 https://www.microsoft.com/net/download

**Comment by iJzFan** [comment]
应该是这个原因,可以把C:\Program Files\dotnet整个文件夹删掉,然后安装最新的sdk。
# # #[orleans issue](https://github.com/dotnet/orleans/issues/4956)

**Comment by iEricZHENG** [comment]
@sunriseyuen 现在呢？

**Comment by iEricZHENG** [comment]
原因：IGrain层使用了System.Threading.Tasks.Extensions中的ValueTask
方式一：如楼上@iJzFan 所说,""把C:\Program Files\dotnet整个文件夹删掉,然后安装最新的sdk(https://www.microsoft.com/net/download),
方式二：将Example中IGrain用到ValueTask的接口改为Task

**Comment by iJzFan** [comment]
也可以把依赖升级到2.1正式版，然后用Microsoft.Orleans.CodeGenerator.MSBuild替换掉Microsoft.Orleans.OrleansCodeGenerator.Build。这样安装多个sdk也没有问题。
