### ISSUE TITLE
EventHandlerExtensions在程序集中寻找EventHandler时抛异常

### ISSUE THREAD

**Issue by feijie999** [RayTale/Ray#16]
![image](https://user-images.githubusercontent.com/23080599/54401377-5ef2fc00-4702-11e9-8378-45b9166200f9.png)
[EventHandlerExtensions](https://github.com/RayTale/Ray/blob/0c8fa786266cbb9a72dc80173396db669bea50f8/Ray.Core/Event/EventHandlerExtensions.cs#L15)

**Comment by u-less** [comment]
问题已经修复，导致这个原因是有些系统object的FullName==Null
