### ISSUE TITLE
是否可以定义一个GuidFollowUnit

### ISSUE THREAD

**Issue by feijie999** [RayTale/Ray#19]
![image](https://user-images.githubusercontent.com/23080599/54609073-20a46680-4a8d-11e9-99bf-3c6abec29b4d.png)
![image](https://user-images.githubusercontent.com/23080599/54609267-927cb000-4a8d-11e9-96f4-0123014e3d4d.png)
这里的命名也有些怪异

**Comment by u-less** [comment]
这几天做了精简，只保留了一个Unit,Guid建议转换为字符串，目前大家对Guid没有强烈的要求，但是要支持会变得很复杂
