### ISSUE TITLE
转账分布式事务中，扣款操作异常

### ISSUE THREAD

**Issue by Godricm** [RayTale/Ray#20]
### 在使用example中使用分布式转账测试时，扣款事件无法正常处理
![0](https://github.com/miusi/musipic/blob/master/RayBugTranfer0.png?raw=true)
![1](https://github.com/miusi/musipic/blob/master/RayBugTranfer1.png?raw=true)

**Comment by u-less** [comment]
问题已经找到，是ShadowGrain跟分布式事务产生的Event不兼容导致的，已经修复

**Comment by SpuerNuomi** [comment]
> 问题已经找到，是ShadowGrain跟分布式事务产生的Event不兼容导致的，已经修复
验证通过
