### ISSUE TITLE
关于简化配置的问题

### ISSUE THREAD

**Issue by feijie999** [RayTale/Ray#21]
![image](https://user-images.githubusercontent.com/23080599/55270351-baafae80-52d8-11e9-8950-350650e46dba.png)
![image](https://user-images.githubusercontent.com/23080599/55270360-c69b7080-52d8-11e9-8619-48906060d7be.png)
这两种配置可否简化来提高易用性？比如在WorkFlowGrain类上面添加[Attribute]和根据Grain名称默认配置消息队列名称？

**Comment by u-less** [comment]
@feijie999 这件事情已经在着手处理，最近又几个提交都是专门优化这个的，可以拉取最新代码看下
