### ISSUE TITLE
数据库操作代码怎么写？

### ISSUE THREAD

**Issue by chenzhe** [RayTale/Ray#3]
我在运行ray 的example 的时候，很好奇想问下，数据库操作应该在那个代码里写，grain 里还是 eventhandle 处理

**Comment by u-less** [comment]
在EventHandle里面

**Comment by chenzhe** [comment]
有corehandler 和  toreadhandler 这两个都可以写数据库操作代码，那么有什么讲究吗？

**Comment by CharlesZHENG** [comment]
https://github.com/RayTale/Docs/blob/master/4.Handler%E4%B9%8BCoreHandler%E7%BC%96%E5%86%99.md

**Comment by iEricZHENG** [comment]
这里有两篇文章：[5.Handler之ToReadHandler编写.md](https://github.com/RayTale/Docs/blob/master/5.Handler%E4%B9%8BToReadHandler%E7%BC%96%E5%86%99.md),[4.Handler之CoreHandler编写.md](
https://github.com/RayTale/Docs/blob/master/4.Handler%E4%B9%8BCoreHandler%E7%BC%96%E5%86%99.md)
