### ISSUE TITLE
The unit test included in this project failed | 这个项目包含的单元测试出错了

### ISSUE THREAD

**Issue by Myosotissylvatica36** [RayTale/Ray#30]
在调用 followUnitContainer.Register(ObserverUnit<long>.From<Account>(serviceProvider)); 代码后抛出异常，原因是由于内部调用tryAdd方法时未能通过，手动抛出异常，不知具体原因

**Comment by u-less** [comment]
@Myosotissylvatica36 因为前期遗留问题，单元测试部分比较粗糙，2.0正式发布后会开始梳理单元测试，虽然先后顺序搞反了，但现在只能这样了，望见谅
