### ISSUE TITLE
可以为这个项目贡献代码吗？

### ISSUE THREAD

**Issue by allen2189** [RayTale/Ray#33]
对orleans有一定的了解了，对你们这个项目也很感兴趣。
如何加入你们，一起维护这个项目？

**Comment by lfzm** [comment]
欢迎欢迎

**Comment by u-less** [comment]
@allen2189 非常欢迎共同维护这个项目，可以加入群里进行交流

**Comment by ElanHasson** [comment]
I am happy to contribute here.

**Comment by u-less** [comment]
@ElanHasson Very welcome，Due to the historical legacy, the project lacks the necessary unit tests, and a lot of work needs to be done later.

**Comment by ElanHasson** [comment]
@luohuazhiyu How can I join the group? Can we perhaps switch to a more accessible location, like gitter?

**Comment by iEricZHENG** [comment]
@ElanHasson  Hi， welcome.

**Comment by ElanHasson** [comment]
Hi @CharlesZHENG  thanks!

@allen2189, we've added a gitter chat, come join us!

https://gitter.im/RayTale/Ray
