### ISSUE TITLE
Multiple attributes named Producer is confusing

### ISSUE THREAD

**Issue by ElanHasson** [RayTale/Ray#43]
There is a `Producer` attribute in the both  RabbitMQ and Kafka assemblies.

Shouldn't this be able to be set by configuration? 

The attribute should be part of the framework and allow you to configure per class.

**Comment by newbe36524** [comment]
I agree too. I think there should be at least four method to configurate.

- default layer as hard code in framework
- attribute based layer (now using )
- fluent api at appilcation setup or somewhere
- configuration from file

**Comment by u-less** [comment]
RabbitMQ and Kafka have different configuration parameters,I don't have a better way to merge them.

**Comment by ElanHasson** [comment]
I think one goal could be to decouple the providers directly from the grain themselves.

Ideally you should be able to just put a `[Producer]` on a `RayGrain`. And it should work based on conventions. (Default provider configured, topic based on type of of the grain).

@newbe36524 is on the right path in  the statements above.

This type of configuration should occur outside of the grain code itself.

I like the idea of named configurations in config files that would map to a fluent API.

**Comment by newbe36524** [comment]
I did that decouple thing in Newbe.Claptrap by adding a EventNotifier, it will notify a context as below:
```cs
    public class EventNotifierContext : IEventNotifierContext
    {
        public IEvent Event { get; set; } = null!;
        public IState CurrentState { get; set; } = null!;
        public IState OldState { get; set; } = null!;
    }
```
One of EventNotifier is main-observer grain connector which I name it EventCenter, it send event from main grain to observer grain.
In this way, we can develop a flexible way to send event from main grain to observer grain.

By the way, I am still looking a better way to replace "the idea of named configurations in config files that would map to a fluent API". I don`t like the reflection thing. I think there should be a better idea.

**Comment by ElanHasson** [comment]
Use expression trees maybe? The cost should be at startup for long running services.

I think it's negligible for config related stuff.

**Comment by newbe36524** [comment]
Performance is not what I mainly concern, but code style thing.
Never mind, leave alone. 
I am waiting your idea and copy that maybe :)
