### ISSUE TITLE
Assemblies should target netstandard2.2 for greater compatibility

### ISSUE THREAD

**Issue by ElanHasson** [RayTale/Ray#44]
https://github.com/RayTale/Ray/blob/cf42e6bbeb11266af2de683cff7d22968c7962c2/src/Directory.Build.props#L3

The libraries should target netstandard2.0 to increase application target runtimes.

**Comment by newbe36524** [comment]
Cause there are some class include in netstandard2.1/etcoreapp2.2/netcoreapp3.1 but not netstandard2.0 ,Such as Memory or somthing for performance.

**Comment by ElanHasson** [comment]
https://github.com/RayTale/Ray/blob/master/Test/Directory.Build.props#L3

Why dual targeting here? are people using 2.1 and 3.1?

**Comment by ElanHasson** [comment]
I just validated `netstandard2.1` works fine.

`netstandard2.0` doesn't have span and a few other things. 

If we can drop `netcoreapp2.2`  we can use `netstandard2.1` .

Let me know if you'd like a pull request for this.

**Comment by ElanHasson** [comment]
Feel free to reject the PR if you need to keep netcoreapp2.2. That is the only reason we can't move forward.
