### ISSUE TITLE
Hope to add a simple registration and login DEMO 

### ISSUE THREAD

**Issue by wangjunjx8868** [RayTale/Ray#63]
希望增加一个简单注册登录的DEMO

**Comment by plz0421** [comment]
个人觉得登录注册不太符合高并发的场景

**Comment by ElanHasson** [comment]
I can see value in registration and login-- basically openid connect implementation backed by RayGrains.

Many sites fail because people can't login at all.

**Comment by wangjunjx8868** [comment]
下载的源码，里面带的三个例子，各种运行不起来，各种错误，缺少的类库即使手动用NUGET也安装不上

**Comment by ElanHasson** [comment]
@wangjunjx8868  which branch? the current working branch is `develop`.

**Comment by wangjunjx8868** [comment]
public sealed class AccountDb : ObserverGrain<long, Account>, IAccountDb
    {
        public Task EventHandle(TransferEvent evt, EventBase eventBase)
        {

            //how to insert to Database in here 
            //此处更新db
            return Task.CompletedTask;
        }
    }

**Comment by ElanHasson** [comment]
Yeah, i see what you mean. It doesn't compile. I'm on it.

**Comment by ElanHasson** [comment]
I'm adding the examples to the main solution so they always will be valid and tested by the commit checks.

So far I've only tested the regular Transfer, but they all compile.

**Comment by ElanHasson** [comment]
@wangjunjx8868 check out the examples now :) 

Specifically the `Transfer` one.

**Comment by ElanHasson** [comment]
@wangjunjx8868 all three examples are fixed.

Please take a look at the `develop` branch.

**Comment by ElanHasson** [comment]
I'm going to close this issue, let me know if you continue to see issues. 

I see you opened up #81. Let's Work on that one.
