### ISSUE TITLE
请问如何让一个客户端随机访问多个silo

### ISSUE THREAD

**Issue by guopenglun** [RayTale/Ray#7]
创建多个silo 。如何让客户端动态的选择silo？
silo数量可能会增加，增加后客户端能动态发现并使用吗？
例如客户端for 1000次。平均的分散到10个silo 。每个100次。
代码应该是什么样的？
不是很清楚该怎么写。谢谢。

**Comment by u-less** [comment]
这个你不用关心，orleans的调度系统会自动根据负载情况进行调度

**Comment by guopenglun** [comment]
哦。这样的话，是有自动发现功能？能很方便的实现热更新？

**Comment by geffzhang** [comment]
@guopenglun Orleans 它不仅仅解决了远程调用问题，其内部还包含了服务发现、负载均衡、高可用等一些处理机制, 很方便实现热更新
