### ISSUE TITLE
Index name has "account" hard coded, should be subtable name

### ISSUE THREAD

**Issue by ElanHasson** [RayTale/Ray#77]
https://github.com/RayTale/Ray/blob/332655463dd0525fe6e5f1bc9362f22ed64d8bff/src/Ray.Storage.SQLServer/Core/SQLServerBuildService.cs#L65-L66

Per convention, the index name should be named after the table name:
```
INDEX account_event_id_unique unique(StateId,TypeCode,UniqueId),
INDEX account_event_Version unique(StateId, Version)
```

Should be 

```
INDEX {subTable.SubTable}_event_id_unique unique(StateId,TypeCode,UniqueId),
INDEX {subTable.SubTable}_event_Version unique(StateId, Version)
```

**Comment by u-less** [comment]
A missed mistake

**Comment by ElanHasson** [comment]
No worries, more eyes == more quality :)
