### ISSUE TITLE
 Cannot find generated GrainReference class for interface 

### ISSUE THREAD

**Issue by wangjunjx8868** [RayTale/Ray#81]
i  make a simple demo,only a interface , inherit  IStock
 

InvalidOperationException: Cannot find generated GrainReference class for interface 'QtShop.IGrains.IStock'

What's the reason?

**Comment by wangjunjx8868** [comment]
Master branch:Transfer  Sample

Transfer.Client

TypeLoadException: Could not load type 'Orleans.GrainDirectory.GlobalSingleInstanceRegistration' from assembly 'Orleans.Core.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by ElanHasson** [comment]
Can you please post a repo ?
